In [1]:
# Importing the libraries
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
from sklearn.compose import ColumnTransformer

In [2]:
dataset = pd.read_csv('Churn_Modelling.csv')
X = dataset.iloc[:, 3:13].values
y = dataset.iloc[:, 13].values

In [3]:

# Encoding categorical data
from sklearn.preprocessing import LabelEncoder, OneHotEncoder
ct = ColumnTransformer([("Country", OneHotEncoder(), [1])], remainder = 'passthrough')
#X = ct.fit_transform(X)

In [4]:
#labelencoder_X_1 = LabelEncoder()
#X[:, 1] = labelencoder_X_1.fit_transform(X[:, 1])
labelencoder_X_2 = LabelEncoder()
X[:, 2] = labelencoder_X_2.fit_transform(X[:, 2])
#onehotencoder = OneHotEncoder(categorical_features = [1])
X = ct.fit_transform(X) #.toarray()
X = X[:, 1:]


In [5]:

# Splitting the dataset into the Training set and Test set
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

# Feature Scaling
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [6]:
# Part 2 - Now let's make the ANN!

# Importing the Keras libraries and packages
import keras
from keras.models import Sequential
from keras.layers import Dense

In [7]:
# Initialising the ANN
classifier = Sequential()

# Adding the input layer and the first hidden layer
classifier.add(Dense(6, kernel_initializer = 'uniform', activation = 'relu', input_dim = 11))

# Adding the second hidden layer
classifier.add(Dense(6, kernel_initializer = 'uniform', activation = 'relu'))

# Adding the output layer
classifier.add(Dense(1, kernel_initializer = 'uniform', activation = 'sigmoid'))

# Compiling the ANN
classifier.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])

# Fitting the ANN to the Training set
classifier.fit(X_train, y_train, batch_size = 10, epochs = 100)

Epoch 1/100
800/800 [==============================] - 4s 2ms/step - loss: 0.5609 - accuracy: 0.7940
Epoch 2/100
800/800 [==============================] - 1s 881us/step - loss: 0.4257 - accuracy: 0.7963
Epoch 3/100
800/800 [==============================] - 1s 873us/step - loss: 0.4279 - accuracy: 0.7923
Epoch 4/100
800/800 [==============================] - 1s 868us/step - loss: 0.4275 - accuracy: 0.7960
Epoch 5/100
800/800 [==============================] - 1s 861us/step - loss: 0.4126 - accuracy: 0.8243
Epoch 6/100
800/800 [==============================] - 1s 885us/step - loss: 0.4062 - accuracy: 0.8286
Epoch 7/100
800/800 [==============================] - 1s 878us/step - loss: 0.4139 - accuracy: 0.8248
Epoch 8/100
800/800 [==============================] - 1s 880us/step - loss: 0.4155 - accuracy: 0.8320
Epoch 9/100
800/800 [==============================] - 1s 874us/step - loss: 0.4101 - accuracy: 0.8350
Epoch 10/100
800/800 [==============================] - 1s 864us/step - los

In [8]:
# Part 3 - Making the predictions and evaluating the model

# Predicting the Test set results
y_pred = classifier.predict(X_test)
y_pred = (y_pred > 0.5)

# Making the Confusion Matrix
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)

In [9]:
y_pred


array([[False],
       [False],
       [False],
       ...,
       [False],
       [False],
       [False]])

In [10]:
cm

array([[1548,   47],
       [ 271,  134]], dtype=int64)

In [15]:
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score

# Summary of the predictions made by the classifier
print(classification_report(y_test, y_pred))
print(confusion_matrix(y_test, y_pred))
print()
# Accuracy score
print('accuracy is',accuracy_score(y_pred,y_test))



              precision    recall  f1-score   support

           0       0.85      0.97      0.91      1595
           1       0.74      0.33      0.46       405

    accuracy                           0.84      2000
   macro avg       0.80      0.65      0.68      2000
weighted avg       0.83      0.84      0.82      2000

[[1548   47]
 [ 271  134]]

accuracy is 0.841
